officialweb/ShenNius.WebBlog/ViewComponents/HeaderNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ShenNius.OfficialWeb.Core.Common;
using ShenNius.OfficialWeb.Core.Domain.Services;

namespace ShenNius.WebBlog.ViewComponents
{
    public class HeaderNavViewComponent : ViewComponent
    {
        private readonly DomainConfig _domainConfig;
        private readonly CmsDomainService _cmsDomainService;

        public HeaderNavViewComponent(IOptionsMonitor<DomainConfig> options, CmsDomainService cmsDomainService)
        {
            _domainConfig = options.CurrentValue;
            _cmsDomainService = cmsDomainService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var list = await _cmsDomainService.GetColumnAsync(_domainConfig.SiteId);           
            return View(list);
        }
    }
}

officialweb/ShenNius.WebBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="keywords" content="@ViewData["keywords"]" />
    <meta name="description" content="@ViewData["Description"]" />
    <environment exclude="Development">
        <link href="~/css/base.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/m.css" rel="stylesheet" asp-append-version="true" />
        <script src="/js/jquery-1.8.3.min.js"></script>
    </environment>
    <environment include="Development">
        <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
        <link href="/css/m.css" rel="stylesheet" asp-append-version="true" />
        <script src="/js/jquery-1.8.3.min.js"></script>
    </environment>
    @RenderSection("css", false)
    @RenderSection("js", false)
</head>
<body>
    @await Component.InvokeAsync("HeaderNav")
    <div class="searchbox">
        <div class="search">
            <form action="@domainConfig.CurrentValue.Host@Url.Action("search","home")" method="get" name="searchform" id="searchform">
                <input name="keyword" id="keyword" class="input_text" placeholder="请输入关键字词" style="color: rgb(153, 153, 153);" type="text">
                <input class="input_submit" value="搜索" type="submit">
            </form>
        </div>
        <div class="searchclose"></div>
    </div>
    <article>
        @RenderBody()
    </article>
    <footer>
        <div class="box">
            <div class="wxbox">
                <ul>
                    <li><img src="/image/wxhuochong.jpg"><span>微信公众号</span></li>
                    <li><img src="/image/mywx.jpg"><span>我的微信</span></li>
                </ul>
            </div>
            <div class="endnav">
                <p><b>站点声明：</b></p>
                <p>Copyright © 2018 52huochong.com All rights reserved.<a href="http://www.miitbeian.gov.cn/" target="_blank"> 浙ICP备19000582号</a></p>
                <p>
                    <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602009921" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">
                        <img src="/image/beian.png" style="float:left;" />
                        浙公网安备 33010602009921号
                    </a>
                </p>
            </div>
        </div>
        <a href="#">
            <div class="top"></div>
        </a>
    </footer>
   
    <script>
        (function () {
            var bp = document.createElement('script');
            var curProtocol = window.location.protocol.split(':')[0];
            if (curProtocol === 'https') {
                bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
            }
            else {
                bp.src = 'http://push.zhanzhang.baidu.com/push.js';
            }
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(bp, s);
        })();
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?ee40cb7a7b9893f41b9c164497e7cea9";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <script src="~/js/echo.min.js"></script>
    <script src="~/js/nav.min.js" asp-append-version="true"></script>
    <script src="/js/comm.js" asp-append-version="true"></script>
</body>
</html>